meta_product_name: "biqom"
meta_title: "be better - biqom"
meta_description: "You find it difficult to implement new habits and become a better version of yourself? Then don't hesitate, biqom is here to help you change that!"
meta_image: "socialcard.png"